backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'mandarin'
    label: 'Mandarin'
    folder: 'content/mandarin'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Recycle Type', name: 'recycleType', widget: 'string' }
      - { label: 'Item Value', name: 'itemValue', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'malay'
    label: 'Malay'
    folder: 'content/malay'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Recycle Type', name: 'recycleType', widget: 'string' }
      - { label: 'Item Value', name: 'itemValue', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'tamil'
    label: 'Tamil'
    folder: 'content/tamil'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Recycle Type', name: 'recycleType', widget: 'string' }
      - { label: 'Item Value', name: 'itemValue', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }