backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: ../../static/img

collections:
  - name: "english"
    label: "English"
    folder: "content/english"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
    - { label: "Language", name: "language", widget: "hidden", default: "english" }
    - { label: "Trashnumber", name: "trashnumber", widget: "string", required: true }
    - { label: "Trashname", name: "title", widget: "string", required: true }
    - { label: "Description1", name: "description1", widget: "string", required: true }
    - { label: "Trash Image", name: "trashimage", widget: "image", required: true }
    #Component Section
    - { label: "Component1", name: "component1", widget: "image", required: false }
    - { label: "TrashCategory1", name: "trashcategory1", widget: "image", required: false }
    - { label: "Component2", name: "component2", widget: "image", required: false }
    - { label: "TrashCategory2", name: "trashcategory2", widget: "image", required: false }
    - { label: "Component3", name: "component3", widget: "image", required: false }
    - { label: "TrashCategory3", name: "trashcategory3", widget: "image", required: false }
    - { label: "Component4", name: "component4", widget: "image", required: false }
    - { label: "TrashCategory4", name: "trashcategory4", widget: "image", required: false }
    #What To Do Section
    - { label: "WhatToDo", name: "whattodo1", widget: "image", required: false }
    - label: "WhatToDoOption1"
      name: "whattodooption1"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "WhatToDo", name: "whattodo1", widget: "image", required: false }
    - label: "WhatToDoOption2"
      name: "whattodooption2"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "WhatToDo", name: "whattodo1", widget: "image", required: false }
    - label: "WhatToDoOption3"
      name: "whattodooption3"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "WhatToDo", name: "whattodo1", widget: "image", required: false }
    - label: "WhatToDoOption4"
      name: "whattodooption4"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    #Do It Well Section
    - { label: "DoItWell1", name: "doitwell1", widget: "image", required: false }
    - { label: "DoItWellDescription1", name: "doitwelldesc1", widget: "string", required: false }
    - { label: "DoItWell2", name: "doitwell2", widget: "image", required: false }
    - { label: "DoItWellDescription2", name: "doitwelldesc2", widget: "string", required: false }
    - { label: "DoItWell3", name: "doitwell3", widget: "image", required: false }
    - { label: "DoItWellDescription3", name: "doitwelldesc3", widget: "string", required: false }
    - { label: "DoItWell4", name: "doitwell4", widget: "image", required: false }
    - { label: "DoItWellDescription4", name: "doitwelldesc4", widget: "string", required: false }
    #Do It Better Section
    - { label: "Do It Better1", name: "doitbetter1", widget: "string", required: false }
    #Second Description
    - { label: "Description2", name: "description2", widget: "string", required: true }