backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: ../../static/img

collections:
  - name: "english"
    label: "English"
    folder: "content/english"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
    - { label: "Language", name: "language", widget: "hidden", default: "english" }
    - { label: "Trash Number", name: "trashnumber", widget: "number", required: true }
    - { label: "Trash Name", name: "title", widget: "string", required: true }
    - { label: "Description1", name: "description1", widget: "string", required: true }
    #Component Section
    - { label: "Component1", name: "component1", widget: "image", required: false }
    - { label: "Trash Category1", name: "trashcategory1", widget: "image", required: false }
    - { label: "Component2", name: "component2", widget: "image", required: false }
    - { label: "Trash Category2", name: "trashcategory2", widget: "image", required: false }
    - { label: "Component3", name: "component3", widget: "image", required: false }
    - { label: "Trash Category3", name: "trashcategory3", widget: "image", required: false }
    - { label: "Component4", name: "component4", widget: "image", required: false }
    - { label: "Trash Category4", name: "trashcategory4", widget: "image", required: false }
    #What To Do Section
    - { label: "What To Do1", name: "whattodo1", widget: "image", required: false }
    - label: "What To Do Option1"
      name: "whattodooption1"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "What To Do2", name: "whattodo2", widget: "image", required: false }
    - label: "What To Do Option2"
      name: "whattodooption2"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "What To Do3", name: "whattodo3", widget: "image", required: false }
    - label: "What To Do Option3"
      name: "whattodooption3"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    - { label: "What To Do4", name: "whattodo4", widget: "image", required: false }
    - label: "What To Do Option4"
      name: "whattodooption4"
      widget: "select"
      options:
        - { label: "Plastic Bin", value: "plasticbin" }
        - { label: "General Bin", value: "generalbin" }
    #Do It Well Section
    - { label: "Do It Well1", name: "doitwell1", widget: "image", required: false }
    - { label: "Do It Well Description1", name: "doitwelldesc1", widget: "string", required: false }
    - { label: "Do It Well2", name: "doitwell2", widget: "image", required: false }
    - { label: "Do It Well Description2", name: "doitwelldesc2", widget: "string", required: false }
    - { label: "Do It Well3", name: "doitwell3", widget: "image", required: false }
    - { label: "Do It Well Description3", name: "doitwelldesc3", widget: "string", required: false }
    - { label: "Do It Well4", name: "doitwell4", widget: "image", required: false }
    - { label: "Do It Well Description4", name: "doitwelldesc4", widget: "string", required: false }
    #Second Description
    - { label: "Description2", name: "description2", widget: "string", required: true }